agoenergy/ptx-boa

.pre-commit-config.yaml, README.md, environment.yaml
Hi Saeed,
I add some files for initial configurations. Coud you help review and approve this pull request?
List of initial setup:
- Add basic information in `README.md`.
- Add `.pre-commit.config.yaml`.
- Add `environment.yaml`.
Thanks and best regards,
Yu-Chi
=> Initial merge from `develop` into `main`

app/ptxboa_functions.py, ptxboa/api.py, ptxboa_mockup.py
@wingechr  changed according to your suggestion. No changes to functionality of mockup app.
=> refactor: pass dimension as parameter to `api.get_dimension`

app/ptxboa_functions.py
- product
- electrolyzer type
- reconversion yes / no
=> 19 improve settings widgets

ptxboa/api.py
this is a first proposal how the data interface between the API and the caller could look like. 
`PtxboaAPI.calculate()` would return a long format pd.DataFrame with the following columns:
- 'process_subtype'
- 'cost_type'
- 'process_type'
- 'scenario'
- 'secproc_co2'
- 'secproc_water'
- 'chain'
- 'res_gen'
- 'region'
- 'country'
- 'transport'
- 'values'
All columns except of `values` are pd.Categorical. Return values from different calls of `.calculate()` can be concatenated and aggregated over different dimensions  subsequently .
=> return random data with api.calculate()

app/ptxboa_functions.py
@joAschauer bei deiner letzten suggestion mit den fstrings hatte sich leider ein fehler eingeschlichen... 
hätte man auch vermeiden können mit CI auf dem develop branch, oder?
=> Fix f string bug

app/ptxboa_functions.py, ptxboa_streamlit.py
using the new ``api.calculate()`` with new data structure in frontend.
=> 24 use ptxboaapicalculate in frontend

app/ptxboa_functions.py, ptxboa/api.py, tests/test_api.py
closes #12 
editing with user data is not implemented yet.
=> make scenario data available from api

app/ptxboa_functions.py, ptxboa_streamlit.py
added some explanatory text boxes in frontend
=> 39 add intro text to all sheets

.pre-commit-config.yaml, ptxboa/api.py, ptxboa/api_data.py
Hi Christian @wingechr,
please have a look, still needs tests and better documentation.
=> Draft: Api data

ptxboa/api.py, ptxboa/api_data.py
Hi Christian @wingechr,
I implemented the dimension parameter code mapping in PtxData. If you find a better name for this method go for it, I really find it confusing with all the different things that are called "dimension" and similar.
=> include mapping function to get dimension parameter code in `PtxData()`

app/ptxboa_functions.py
@joAschauer thanks for pointing this out.
=> fix: duplicate widget ID error (#74)

app/ptxboa_functions.py, ptxboa_streamlit.py
This makes it possible to pass changed user data to api.get_input_data (#90)
the lastest change is recorded if duplicate entries in edit input data index columns are found (#79)
=> use data editor callback to update user data

app/ptxboa_functions.py, ptxboa/api.py, ptxboa_streamlit.py
Hi Markus @markushal,
the user data is now passed to the backend, give it a try. I had to remove the subregions from `res_costs` for the world map as otherwise the color for e.g. Argentina got displayed incorrectly when a value was changed for it.  
In the long run, I guess we could think about making `res_costs` a session state variable.
=> User data in calculations

app/ptxboa_functions.py, ptxboa/api.py, ptxboa/api_data.py
I added some new data to the input data tab. Displaying and editing works, but I needed to pass two new parameters to the display and register_user_changes functions to pass information that is not contained in the 2D table. I hope it did not become too complex now...
=> 85 display and edit other data

app/ptxboa_functions.py
=> move display of plotly figure 

.github/workflows/test.yaml, requirements.txt, tests/test_ptxboa_streamlit.py
=> introduce first test for streamlit app

ptxboa/api_data.py
Hi @markushal, (cc @wingechr)
closes #120
Christian and I decided to first try option 3. in #120. This gives a performance improvement of Factor 10.6 for calculations without custom user data.
=> Increase performance with parameter selection on key

app/sidebar.py
added include subregions to session state, now the toggle works again. closes #119
=> add `include_subregions` to session state

app/ptxboa_functions.py, ptxboa_streamlit.py
=> show units in user changes and rename columns

app/plot_functions.py
=> use discrete color map for cost category barplots

README.md
resolves #126
we needed to switch to venv and pip in #15
=> update development instructions for virtualenv

app/ptxboa_functions.py
still needs some explanation comments in the code, messy stuff in here...
=> reject user input for missing data points in input data

app/ptxboa_functions.py
=> fix not editable first line in df

app/context_data.py, app/tab_country_fact_sheets.py
fixes #171 
was not only present for denmark but whenever a string value was present in the context data
=> Context data fixes

tests/test_api.py
@wingechr can you check this please?
=> 317-bug-demand-country-select-box-lists-supply-regions

flh_opt/collect_cached_optimization_results.py, offline_optimization_script.py
added a first draft for collecting chached optimization data
=> optimization evaluation

flh_opt/__init__.py, ptxboa/api_optimize.py
the cache erroneously contained data that was not part of the optimization results
=> fix caching of optimizer

app/sidebar.py, ptxboa/api.py
=> Dynamic res dropdown options

.streamlit/config.toml, ptxboa/api_optimize.py
=> 360 fix parallel optimization of same data write access

app/tab_costs.py, app/tab_deep_dive_countries.py, ptxboa_streamlit.py, tests/test_ptxboa_streamlit.py
fixes #325
also improve performance: costs are only calculated when needed for a specific tab
=> use buttons instead of tabs

app/user_data.py
=> always show correct unit in modified data list

app/layout_elements.py, app/tab_input_data.py
=> Direct air capture and desalination data presentation

app/sidebar.py
=> put settings in expanders and hide additional settings by default

app/layout_elements.py
also put footer in streamlit cache
Fixes #264
=> adapt Agora links in footer

app/layout_elements.py
=> Costs by region Graph: select top ten as default setting

app/tab_certification_schemes.py, app/tab_costs.py, app/tab_country_fact_sheets.py, app/tab_deep_dive_countries.py, app/tab_input_data.py, app/tab_literature.py, app/tab_market_scanning.py, app/tab_optimization.py, app/tab_sustainability.py
=> improve "What is this?" boxes

app/plot_functions.py
=> cost graphs: move current selection marker down if costs are negative

app/plot_functions.py
=> fix Interest-rate unit error on choropleth map

app/sidebar.py, app/tab_costs.py
=> costs by supply chain: by default only show selected electrolyser technology

app/plot_functions.py, app/tab_optimization.py, md/info_optimization_results.md
I also fixed some units and improved the colors in the profiles plot
=> 415 add storage capacity and storage costs to optimization results table

app/plot_functions.py, requirements.txt
=> for stacked areas, only add trace if not all are zero

app/plot_functions.py
=> highlight source region on maps

app/layout_elements.py, app/ptxboa_functions.py, app/tab_input_data.py
Fixes #229
also fixed the index name of the full load hours input data
=> fix units for green iron reduction and transportation process data

app/ptxboa_functions.py
=> remove electricity costs from specific costs input data

.streamlit/config.toml
=> remove hamburger menu at top right

app/layout_elements.py
=> add note for unit in supply_chain cost comparison

.bumpversion.cfg, .github/workflows/publish.yaml, CHANGELOG.md, Dockerfile, README.md, app/tab_info.py, app/tab_input_data.py, ptxboa_streamlit.py, requirements.txt
=> 538 in tool capex unit should be usdkw but it says usdmw
