agoenergy/ptx-boa

- ptxboa/api.py
- tests/test_api.py
hi @markushal, 
maybe still some minor issues here:
~~- missing values that are empty strings when `long_names=False` are returned as NaN. is that okay? Otherwise, I can replace Nans with empty strings again.~~
**Update:** Empty values are now empty strings and not Nans also for `long_names=True`
- if a parameter code/name pair is not defined in api.dims, the long name will also be NaN even if a code was there before. ~~We could check in a test that this is not happening~~ **Update:**: there is now a test that should cover this.
> add option to replace codes with long names in input data

- app/ptxboa_functions.py
- tests/test_ptxboa_functions.py
Hi guys, the reason why there was not costs data displayed in the app #68   was that the removal of subregions failed, because it tested for empty subregion codes in ``api.get_dimension("region"), and these changed from being NaN to now being empty strings. 
I adjusted the check in ``remove_subregions``, and the app is working fine now, but I wonder if this is how we want to keep it? 
I also added a unit test for the function, and i created a new python file for tests of the ``ptxboa_functions`` module. Is this the correct way of doing it?
> 68 bug no cost output in app

- app/ptxboa_functions.py
closes #73 
same problem as in #68, backend returns empty string for missing values.
> Fix: empty input data (#73)

- app/ptxboa_functions.py
Hi guys, i improved the layout and the hover text for the world map (see #54 )
> 54 design of the map template

- app/ptxboa_functions.py
sorry, I had to remove the "ten cheapest" option completely. We dont need it anymore, I think.
> remove ten cheapest option, obsolete

- app/ptxboa_functions.py
- ptxboa_streamlit.py
- tests/test_ptxboa_functions.py
I moved the ``settings`` dictionary to ``st.session_state["settings"]``. keep in mind that unittests do not work for functions that call ``st.session_state``. This is why I removed the legacy ``calculate_results`` function and the associated test. 
We should try to set up the streamlit testing framework #112
@joAschauer I hope these changes do not conflict with the work you are currently doing
> 105 move settings to session state

- app/ptxboa_functions.py
- app/sidebar.py
- app/tab_input_data.py
- ptxboa_streamlit.py
Hi Markus, 
this proposal would close #133, and close #134 I data editing mode is turned on, we show a warning above the tabs and the edited data table below the warning in an expander. What do you think about this design?
One issue with this approach: the app switches to the first tab (dashboard) when the data editing mode is changed.
> Visibility of data editing mode

- app/layout_elements.py
- ptxboa_streamlit.py
The wide layout which is currently used makes it difficult that the app looks okay both on large and smaller screens. This PR uses the centered layout but with increased width. See https://discuss.streamlit.io/t/can-not-set-page-width-in-streamlit-1-5-0/21522/5
I also put the data selection widgets above the cost barplots.
> Restrict page width

- app/ptxboa_functions.py
> change order of cost type columns to match position in chain

- app/layout_elements.py
- app/plot_functions.py
- app/ptxboa_functions.py
- app/tab_dashboard.py
- ptxboa_streamlit.py
> Output unit for supply chains comparison

- app/ptxboa_functions.py
- app/tab_dashboard.py
- ptxboa_streamlit.py
- requirements.txt
resolves #157
this introduces a new dependency `streamlit-antd-components`
> remove infobox and add option switch between tabs programatically

- app/tab_certification_schemes.py
- app/tab_country_fact_sheets.py
- app/tab_dashboard.py
- app/tab_deep_dive_countries.py
- app/tab_input_data.py
- app/tab_literature.py
- app/tab_sustainability.py
bundled a few parts in functions, this makes potential future merge conflicts less likely.
also removed columns in sustainability tab and added a Title to the references List.
resolves #156
> Element grouping with bordered containers

- app/ptxboa_functions.py
xref #177 
it would be quite involved to validate the user input for missing data. 
The data gaps need to be fixed before publishing. For now, we show a warning above the data editor that empty values should not be modified.
> add warning for draft version to not modify missing data points

- app/ptxboa_functions.py
- app/user_data_from_file.py
- ptxboa/api.py
- ptxboa/api_data.py
- tests/test_api_data.py
- tests/test_user_data/non_existent_index_user_data.csv
- tests/test_user_data/non_numeric_empty_user_data.csv
- tests/test_user_data/non_numeric_nan_user_data.csv
- tests/test_user_data/non_numeric_string_user_data.csv
- tests/test_user_data/param_above_range_user_data.csv
- tests/test_user_data/param_below_range_user_data.csv
- tests/test_user_data/too_many_columns_user_data.csv
- tests/test_user_data/valid_user_data.csv
- tests/test_user_data/wrong_column_name_user_data.csv
- tests/test_user_data_from_file.py
Hi Markus @markushal,
this fixes your issue with the missing flow code (https://github.com/agoenergy/ptx-boa/pull/184#issuecomment-1852399442). 
`target_country_code` is still missing and thus not editable by the user, is this intentional?
> add `flow_code` column to `user_data` dataframe

- app/layout_elements.py
- app/plot_functions.py
- app/ptxboa_functions.py
- app/tab_dashboard.py
- app/tab_deep_dive_countries.py
- ptxboa_streamlit.py
@joAschauer please have a look at this. I implemented a way to compare costs with and without considering user data changes. I find this very helpful in understanding the effects of modifying input data. 
I am sure the implementation and representation of the data can still be improved...
> 188 compare results with and without user changes

- app/excel_download.py
- app/layout_elements.py
- app/ptxboa_functions.py
- app/tab_deep_dive_countries.py
- app/tab_input_data.py
- requirements.txt
Streamlit download button currently expects its data to be available when declaring the button. This means, we always have to keep the excel file streams for each dataframe in memory and the conversion to excel is made whenever any value changes in a dataframe.
If that is acceptable, this PR is ready.
> Add excel download button

- app/ptxboa_functions.py
- app/sidebar.py
- app/tab_costs.py
Fixes #410
subregion inclusion is only realized in the bar plot comparison and not yet in the global map.
> include selected subregion in global cost comparison

- app/tab_deep_dive_countries.py
> deep dive countries switch from sac.segmented to sac.buttons

- app/tab_optimization.py
- ptxboa_streamlit.py
> don't calculate all results when in optimization tab

- app/tab_market_scanning.py
> use distance to France as transport distances to

- app/ptxboa_functions.py
Fixes #445
For chains that don't need CO2, "secproc_co2" is set to None, otherwise, the session state value is used.
> adapt "secproc_co2" in `calculate_results_list()` based on chain

- app/plot_functions.py
- selected region was not highlighted in input data maps
- when a value is nan (e.g. JOR, Wind Offshore) do not plot the point
- consider no-data points in hovers
> fix highlight of selected subregion and hover nans

- app/layout_elements.py
- app/ptxboa_functions.py
- app/tab_input_data.py
Fixes #447
I would prefer if parameters that are hard coded in optimize function (storage capacity) are not part of the table. Is it possible to put them to the st.caption of the storage expander?
> move storage parameters to dedicated table

- ptxboa/api_calc.py
- ptxboa/api_optimize.py
- tests/test_api.py
- tests/test_api_data.py
> fix storage cost  (capacity) using CAP_F
